# Generated by Django 5.2.3 on 2025-06-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querynestapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='student',
            name='register_number',
            field=models.CharField(default='CCE24CS063', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
