# Generated by Django 5.2.3 on 2025-06-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querynestapp', '0002_rename_created_at_answer_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='test123', max_length=100),
            preserve_default=False,
        ),
    ]
